from subprocess import call
import subprocess
import os

clear = lambda: os.system('cls')
clear()
call('color 4', shell=True)
print(' /$$        /$$$$$$   /$$$$$$  /$$$$$$ /$$   /$$')
print('| $$       /$$__  $$ /$$__  $$|_  $$_/| $$$ | $$')
print('| $$      | $$  \ $$| $$  \__/  | $$  | $$$$| $$')
print('| $$      | $$  | $$| $$ /$$$$  | $$  | $$ $$ $$')
print('| $$      | $$  | $$| $$|_  $$  | $$  | $$  $$$$')
print('| $$      | $$  | $$| $$  \ $$  | $$  | $$\  $$$')
print('| $$$$$$$$|  $$$$$$/|  $$$$$$/ /$$$$$$| $$ \  $$')
print('|________/ \______/  \______/ |______/|__/  \__/')
print(' ')                                         
print('*******************************************************')
print('Welcome to my toolbox! Insert your admin credentials.  ')
print('*******************************************************')
print(' ')
print(' ')
while True:
    option2 = input('Username: ')
    if option2 in ["Facu", "Mel"]:
        break

if option2 in ["Facu", "Mel"]:
    option3 = input('Password: ')
    if option3 in ["1234", "090393"]:
        clear()
        call('color 3', shell=True)
        print('▒███████▒▓█████  ██▀███   ▒█████     ▓█████▄  ▄▄▄     ▓██   ██▓')
        print('▒ ▒ ▒ ▄▀░▓█   ▀ ▓██ ▒ ██▒▒██▒  ██▒   ▒██▀ ██▌▒████▄    ▒██  ██▒')
        print('░ ▒ ▄▀▒░ ▒███   ▓██ ░▄█ ▒▒██░  ██▒   ░██   █▌▒██  ▀█▄   ▒██ ██░')
        print('▄▀▒   ░▒▓█  ▄ ▒██▀▀█▄  ▒██   ██░   ░▓█▄   ▌░██▄▄▄▄██  ░ ▐██▓░')
        print('▒███████▒░▒████▒░██▓ ▒██▒░ ████▓▒░   ░▒████▓  ▓█   ▓██▒ ░ ██▒▓░')
        print('░▒▒ ▓░▒░▒░░ ▒░ ░░ ▒▓ ░▒▓░░ ▒░▒░▒░     ▒▒▓  ▒  ▒▒   ▓▒█░  ██▒▒▒') 
        print('░░▒ ▒ ░ ▒ ░ ░  ░  ░▒ ░ ▒░  ░ ▒ ▒░     ░ ▒  ▒   ▒   ▒▒ ░▓██ ░▒░') 
        print('░ ░ ░ ░ ░   ░     ░░   ░ ░ ░ ░ ▒      ░ ░  ░   ░   ▒   ▒ ▒ ░░')  
        print('  ░ ░       ░  ░   ░         ░ ░        ░          ░  ░░ ░    ') 
        print('░                                     ░                ░ ░     ')
        print(' ')
        print(' ')
        print('**************************************************************')
        print('                      CHOOSE AN OPTION                        ')
        print(' ')
        print('   1- Find full name')
        print(' ')
        print(' ')
        print('   !- Dangerous options')
        print('**************************************************************')
        print(' ')
        print(' ')
        while True:
            choose = input(': ')
            if choose in ["1", "!"]:
                break

if choose == "1":
    clear()
    call('color 6', shell=True)
    print('Select the database you want to check:')
    print(' ')
    print('**************************')
    print('1- 1°1                   *')
    print('2- 1°2                   *')
    print('3- 1°3                   *')
    print('4- 1°4                   *')
    print('5- 1°5                   *')
    print('6- 1°6                   *')
    print('7- 1°7                   *')
    print('8- 1°8                   *')
    print('9- 1°9                   *')
    print('10- 1°10                 *')
    print('*************************')
    print(' ')
    while True:
        database = input(': ')
        if database in ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]:
            break

elif choose == "!":
    clear()
    call('color 4', shell=True)
    print('ERROR 999: Unauthorized access detected.')

if database == "1":
    clear()
    print('1°1 Database 07/07/22:')
    print(' ')
    print(' ')
    print('****************************************')
    print('BRITANY ALVAREZ ECHENIQUE')
    print('PAMELA LUISANA ALVAREZ PEREIRA')
    print('VALENTINA ARELLANO DE LOS SANTOS')
    print('PRISCILA MICAELA BARBOZA SEQUEIRA')
    print('NARELA YAZMIN CARDOZO MAC EACHEN')
    print('ABRIL LUANA COLMAN MURIEL')
    print('WANDA DOMINIQUE CORREA AQUINO')
    print('JONATHAN MAXIMILIANO COTTO FERNANDEZ')
    print('DILAN FERNANDO DA COSTA BARRUTHE')
    print('FEDERICO DA SILVA FERNANDEZ')
    print('Milagros Agustina DUARTE GONZALEZ')
    print('LUCIANA FERNANDEZ LORENZO')
    print('LUCAS NAHUEL FLORES GARCÍA')
    print('LUANA ANTONELLA GARCIA CORREA')
    print('THIAGO GABRIEL GONZALEZ MORALES')
    print('MELANIE LIZETTE GONZÁLEZ NOGUEIRA')
    print('ERICK BRIAN KETTURKAT LOPEZ')
    print('LUDMILA ABRIL LEDESMA GONZALEZ')
    print('THIAGO NAHUEL MACHADO PIAGGIO')
    print('SANTIAGO SEBASTIAN MENDEZ SABATER')
    print('ITSUKI MATHIAS NAVARRO ACEVEDO')
    print('CAMILA VICTORIA OLIVERA ACEREDO')
    print('FACUNDO ORTIZ FERREIRA')
    print('NICOL AYELEN PASIO MELGAREJO')
    print('BRISA MACARENA RODRIGUEZ CRUZ')
    print('MATEO THIAGO SILVA PEREIRA')
    print('SOFIA BELEN SILVA PRIORI')
    print('BRYAN SUAREZ SUAREZ LEYES')
    print('****************************************')

elif database == "2":
    clear()
    print('1°2 Database 07/07/22:')
    print(' ')
    print(' ')
    print('****************************************')
    print('ROCIO AYMAR ACOSTA SILBERA')
    print('ZOE VICTORIA ANDRADA ARAUJO')
    print('WAIRA YAZMIN ARAUJO MARTINEZ')
    print('MELINA BENTANCOR RODRIGUEZ')
    print('VANINA AYELEN CARDOZO MAC EACHEN')
    print('DAMIAN EDUARDO CASTRO ROSALES')
    print('JAZMÍN CORREA DIAZ')
    print('AYLEEN DE SOSA JAUREGUI')
    print('THIAGO VALENTIN DIAZ CABRERA')
    print('AMBAR MAGALY ECHAVES RAMOS')
    print('LUANA BELEN ESPONDABURU GONZALEZ')
    print('DAYANA ELISA GALIANO GUERRERO')
    print('FACUNDO NAHUEL GARCIA MARTINEZ')
    print('CAMILA NATALY GOMEZ PELLEGRINI')
    print('LUCIANO HERNANDEZ GONZALEZ')
    print('LUCAS EMILIANO MARQUEZ MARTINEZ')
    print('ANA LUCIA MESONE FERNANDEZ')
    print('TATIANA NICOLE MIGUEZ FERNANDEZ')
    print('DIEGO GIANFRANCO MONTEBELLO MACIEL')
    print('NEUSA JLARIS PEREIRA BARRAGAN')
    print('THIAGO BENJAMIN PRESTES PEIXOTO')
    print('VALENTINA ALEJANDRA RIVERO IGLESIAS')
    print('AARON SEBASTIAN RODRIGUEZ GONZALEZ')
    print('VALENTINA CAMILA RODRIGUEZ SICCO')
    print('ALAN KATRIEL ROSALES DIAZ')
    print('FACUNDO SILVEIRA RAMOS')
    print('TIZIANO NAIM SISNANDEZ MARTINEZ')
    print('LAUTARO SUGO FERREIRA')
    print('MAITE LUCIA VELAZCO LOPEZ')
    print('****************************************')

elif database == "3":
    print('1°3 Database 09/07/22:')
    print(' ')
    print(' ')
    print('****************************************')
    print('MARCOS VALENTÍN ACEVEDO ARCE')
    print('AVRIL ANTONELLA ARAP PAPA')
    print('RODRIGO IGNACIO AVIEGA DIAZ')
    print('EUNICE LUCERO BARCELÓ NUÑEZ')
    print('ANDREA PATRICIA BRITES URBINA')
    print('XIOMARA MICAELA COUBROUGH OLIVIERO')
    print('YAMILA DAVILA FARIAS')
    print('CESAR SAMUEL DE LOS SANTOS GALLO')
    print('DENIS ISMAEL FLORES CARDOZO')
    print('LOANA TAMARA FONSECA DUJI')
    print('ALAN YANDEL GARCIA RODRIGUEZ')
    print('YANAINA JAZMIN GOMEZ PROL')
    print('MATEO IGLESIAS VASCO')
    print('ERIKA YAZMIN LIMA SILVEIRA')
    print('INAE MELO DE LOS SANTOS')
    print('LUCAS BENJAMIN MENDEZ RANCHEL')
    print('RODRIGO VALENTIN NUÑEZ CASURIAGA')
    print('XIOMARA NICOLE PEREYRA LOPEZ')
    print('AARON PÉREZ ARIAS')
    print('TATIANA CAMILA RODRIGUEZ ALVAREZ')
    print('DAVID SAMUEL RODRIGUEZ GIMENEZ')
    print('MARTÍN ENZO ROMERO HERNÁNDEZ')
    print('EVELYN PATRICIA RUIZ BARBOZA')
    print('MAURICIO RODRIGO SILVERA LORENZO')
    print('PRISCILLA SOLDINI MATEOS')
    print('THIAGO JESUS SOSA CASTRO')
    print('MATTEO MAXIMILIANO TARRAGONA LATAPIE')
    print('****************************************')

elif database == "4":
    print('1°4 Database 09/07/22:')
    print(' ')
    print(' ')
    print('****************************************')
    print('JULIETA AYELEN ADINOLFI RIZZO')
    print('MORENA BENITEZ SIMONELLI')
    print('GEORGINA BELÉN CABRERA DE LOS SANTOS')
    print('SANDER MICHEL CASTRO MARTINEZ')
    print('MATHÍAS AGUSTÍN COPPOLA CAMACHO')
    print('ELIZABETH SUSAN DE POI RIOS')
    print('ELIAS EZEQUIEL DUARTE TERUEL')
    print('ELÍAS FERNÁNDEZ')
    print('GIANNA CAMILLE FILIPPONI FERNANDEZ')
    print('LUHANA ZAMIRA FLORES MERJER')
    print('MAIA VANINA FURTADO GONZALEZ')
    print('KATHERINE ROMINA GOMEZ RIOS')
    print('LARA FLORENCIA GUEDES CARDOZO')
    print('LUCAS NAHUEL GUTIERREZ SAN MARTIN')
    print('MAIA BELEN IFRAN LEGUIZAMON')
    print('ALISON DAYANA LASO ROBAINA')
    print('JUAN MANUEL LOPEZ ACOSTA')
    print('MELANIE NAIARA MACEDO OLIVERA')
    print('THIAGO JESUS MERLI DE NOBREGA')
    print('AXEL LAUTARO MONTIEL FERREIRA')
    print('FACUNDO MATIAS PIBETE MARTINEZ')
    print('VICTORIA SARAI RÍOS ACOSTA')
    print('ANALIA MAYTE ROCHA AGUIAR')
    print('MELINA RODRIGUEZ ALVEZ')
    print('JASON JAVIER ROMERO VÁZQUEZ')
    print('DELFINA RUIZ OTERO')
    print('SOFIA SOLEDAD SEGOVIA RODRIGUEZ')
    print('LUCAS EZEQUIEL SEQUEIRA FILGUEIRA')
    print('AGUSTINA BELEN SILVERA PINTOS')
    print('LUZMILA MACARENA SOSA LACUESTA')
    print('****************************************')
